### ISSUE TITLE
support reporting star counts

### ISSUE THREAD

**Issue by detrout** [detrout/long-rna-seq-condor#11]
Feature request from lab:

Have STAR generate its count information as we think that is more comparable to htcount style data. (Because it shouldn't include the multi-reads like RSEM's expected_count field).

Generating the file requires adding ```--quantMode GeneCounts``` to the STAR command line. I need to test to see if adding that does anything to the generated BAM files.

They'd like a generated count file that merges the different library results like what makersemcsv does. But its unclear what columns to provide as star outputs 3 count columns in ReadsPerGene.out.tab. (I think the request was for just the unstranded column?)

**Comment by detrout** [comment]
Open question, should makersemcsv be extended to handle the STAR file? should we have a new file makestarcsv? or rename the whole thing makelibrarycsv?

**Comment by saupchurch** [comment]
It seems that what is really being requested here is a summarized counts output for the libraries specified in the library `tsv` file.  Since the counts could come from either STAR or RSEM (or indeed both if desired) it seems like the thing to do is have a `summarizecounts.py` with an option telling it to use either the STAR or RSEM counts as input.

**Comment by detrout** [comment]
Office debate leads to thinking the program that generates summary results should be called "getquantresults" which replaces current makersemcsv. This also implies that we should have second program for processing the star results could be called "getalignerresults"

**Comment by detrout** [comment]
Implemented as a stand alone script called make-star-csv (if installed) in the module woldlab.makestarcsv in 635fb0d and with a bit of installation help in 03c3666
